name: Build Android App
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ?? Checkout
        uses: actions/checkout@v4

      - name: ?? Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: ?? Install dependencies
        working-directory: ./mobile_app
        run: npm install

      - name: ?? Build APK
        working-directory: ./mobile_app
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          npx eas-cli init --non-interactive --force
          npx eas-cli build --platform android --profile preview --non-interactive
